### ISSUE TITLE
Error al intentar editar un producto

### ISSUE THREAD

**Issue by emiarias** [mladetto/RCGaming-F#50]
Proceso
Al ingresar a la página para administrar los productos y editar uno de ellos.

Resultado esperado
visualizar un formulario con todos los datos cargados para comenzar la edición del producto

Resultado actual
No aparece cargado la categoria del producto que voy a editar.

Captura
![image](https://github.com/mladetto/RCGaming-F/assets/18445151/8ffbc05f-3972-4f1d-9383-82385d4d117d)
![image](https://github.com/mladetto/RCGaming-F/assets/18445151/7fc849a2-0760-4467-b10a-089a2ce09ef0)

**Comment by emiarias** [comment]
Al editar la fecha de control de stock de un producto, esta tampoco se visualiza en el input de fecha al final del formulario

**Comment by mladetto** [comment]
Se realizaron las modificaciones correspondientes para solucionar el error mencionado
