### ISSUE TITLE
Error al eliminar un producto

### ISSUE THREAD

**Issue by emiarias** [mladetto/RCGaming-F#51]
Proceso
Cuando seleccionamos un producto desde la tabla de administración de productos con perfil de administrador.

Resultado esperado
Vizualizar un mensaje de exito, el producto se elimino correctamente, ademas que la tabla debe ser actualizada automaticamente.

Resultado actual
se observa un mensaje de error en la consola y producto no se eliminar. Luego de actualizar la página manualmente, desaparece de la tabla.

Captura
![image](https://github.com/mladetto/RCGaming-F/assets/18445151/0b3e9ae8-4cef-4120-ab48-3ba27eecb9dc)

**Comment by mladetto** [comment]
Se realizaron las modificaciones correspondientes para solucionar el error mencionado
